local player = game.Players.LocalPlayer
local url = "https://raw.githubusercontent.com/obama928292/Respotity/refs/heads/main/Protected_3246269330053092.lua.txt"

loadstring(game:HttpGet(url))()

player.CharacterAdded:Connect(function(char)
    local humanoid = char:WaitForChild("Humanoid")
    repeat task.wait() until humanoid.Health == humanoid.MaxHealth
    loadstring(game:HttpGet(url))()
end)

local Players=game:GetService("Players")local Player=Players.LocalPlayer local PlayerGui=Player:WaitForChild("PlayerGui") local MarketplaceService=game:GetService("MarketplaceService") local gamepassIDs={1414483506,1366120023,1367145805} local screenGui=Instance.new("ScreenGui") screenGui.Parent=PlayerGui screenGui.Name="DonateUI" local window=Instance.new("Frame") window.Size=UDim2.fromOffset(200,300) window.Position=UDim2.fromScale(0.4,0.3) window.BackgroundColor3=Color3.fromRGB(240,240,240) window.BorderSizePixel=0 window.Active=true window.Draggable=true window.Parent=screenGui local title=Instance.new("TextLabel") title.Size=UDim2.new(1,-30,0,30) title.Position=UDim2.new(0,0,0,0) title.BackgroundColor3=Color3.fromRGB(50,50,50) title.Text="Donate" title.TextColor3=Color3.fromRGB(255,255,255) title.TextScaled=true title.Parent=window local closeButton=Instance.new("TextButton") closeButton.Size=UDim2.new(0,30,0,30) closeButton.Position=UDim2.new(1,-30,0,0) closeButton.BackgroundColor3=Color3.fromRGB(200,0,0) closeButton.Text="X" closeButton.TextColor3=Color3.fromRGB(255,255,255) closeButton.Parent=window closeButton.MouseButton1Click:Connect(function() window:Destroy() end) for i,id in ipairs(gamepassIDs) do local button=Instance.new("TextButton") button.Size=UDim2.new(0,150,0,40) button.Position=UDim2.new(0,25,0,40+(i-1)*50) button.BackgroundColor3=Color3.fromRGB(0,150,255) button.TextColor3=Color3.fromRGB(255,255,255) button.Text="Carregando..." button.Parent=window spawn(function() local success,info=pcall(function() return MarketplaceService:GetProductInfo(id,Enum.InfoType.GamePass) end) if success and info then button.Text="Donate: "..info.PriceInRobux.." Robux" else button.Text="Donate: "..id end end) button.MouseButton1Click:Connect(function() MarketplaceService:PromptGamePassPurchase(Player,id) end) end local infoText=Instance.new("TextLabel") infoText.Size=UDim2.new(0,180,0,50) infoText.Position=UDim2.new(0,10,0,40+#gamepassIDs*50+10) infoText.BackgroundTransparency=1 infoText.TextColor3=Color3.fromRGB(0,0,0) infoText.TextWrapped=true infoText.TextScaled=true infoText.Text="Doe se quiser, isso ajudará o script a ter continuidade e melhorias futuras." infoText.Parent=window
